### ISSUE TITLE
[BUG] I cant change test ads to real ads

### ISSUE THREAD

**Issue by mani144** [Poing-Studios/godot-admob-android#104]
Greetings,

i have been testing this plugin in for a while, it does work great.

however in order to change my ads from test ads to producation: i followed the steps but could not change it to real.
it was always shown test ads.

this is the log that i got:
`Publisher misconfiguration: Failed to read publisher's account configuration; please check your configured app ID. Received app ID: ca-app-pub-3555349068948156~3604561997. `

androidmainfest.xml file :
   `     <meta-data
            tools:replace="android:value"
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-3555349068948156~3604561997"/> `

**Comment by gumaciel** [comment]
Hello @mani144 , this error is from UMP and you don't need to, so no need to worry about that, just if you are going to use UMP for GDPR or something: https://stackoverflow.com/questions/68457966/failed-to-read-publishers-account-configuration-please-check-your-configured-a

`androidmanifest.xml` seems to be right

also read this message I put on the Discussion: https://github.com/Poing-Studios/godot-admob-android/discussions/77#discussioncomment-2143195

**Comment by mani144** [comment]
@gumaciel i will try to remove UMP . i think its the best thing

**Comment by gumaciel** [comment]
I think you don't need to worry about the UMP, are you getting this message when you initialize the App? Or when you call the method `MobileAds.request_user_consent()`?

**Comment by mani144** [comment]
> I think you don't need to worry about the UMP, are you getting this message when you initialize the App? Or when you call the method `MobileAds.request_user_consent()`?

i did couple of tests.... 
when i used MobileAds.request_user_consent() the error appered. 
i tried to re run it without this command and found out that 
if i asked for load_reward the same error apeers

**Comment by gumaciel** [comment]
Very strange, please try to join in on our Discord, maybe we can help you: https://discord.gg/YEPvYjSSMk

**Comment by mani144** [comment]
@gumaciel thanks, already did that.

**Comment by mani144** [comment]
I learned that there must be two condition to make work:

first, don't put ur testing device in unit test ( this will break the ads policy but i think if u did it once its ok )

In my case, I had to create GDPR to remove the problem. 

i don't know the new google play rules but it seems this is very important
