### ISSUE TITLE
Need tutorial

### ISSUE THREAD

**Issue by hani09876** [Poing-Studios/godot-admob-android#105]
I am from your YouTube channel. Would you please make a tutorial on how
To build a ads plugin.  Please 🥺🥺🥺🥺🙏🙏. I need to learn

**Comment by gumaciel** [comment]
hello, sorry but I don't have much time to make tutorials on how to make plugins for Godot, maybe in the future I will, but currently it's impossible for me.

I have other plans now, which are: improving documentation and making the plugin ready to support version 4.0 that is already coming

maybe this help you: https://github.com/Poing-Studios/godot-admob-android/wiki/Android-Plugin#developing

**Comment by hani09876** [comment]
> hello, sorry but I don't have much time to make tutorials on how to make plugins for Godot, maybe in the future I will, but currently it's impossible for me.
> 
> I have other plans now, which are: improving documentation and making the plugin ready to support version 4.0 that is already coming
> 
> maybe this help you: https://github.com/Poing-Studios/godot-admob-android/wiki/Android-Plugin#developing

Then please add a ironsource ads plugin. Please

**Comment by gumaciel** [comment]
Hi, if you are talking about Mediation, we are already seeing this possiblity: #28

**Comment by hani09876** [comment]
> Hi, if you are talking about Mediation, we are already seeing this possiblity: #28 

How

**Comment by gumaciel** [comment]
Check this link: https://developers.google.com/admob/android/mediation/ironsource

You will need to clone this repository and do the things the AdMob is asking for from here: https://developers.google.com/admob/android/mediation/ironsource#step_3_import_the_ironsource_sdk_and_adapter

**Comment by gumaciel** [comment]
we are trying to see a way to do this automatically without requiring the user to download and build on their own

if you are with doubts about building, this might help you: https://github.com/Poing-Studios/godot-admob-android/wiki/Android-Plugin#developing

**Comment by hani09876** [comment]
> we are trying to see a way to do this automatically without requiring the user to download and build on their own
> 
> if you are with doubts about building, this might help you: https://github.com/Poing-Studios/godot-admob-android/wiki/Android-Plugin#developing

Can i connect with you discord or Twitter

**Comment by gumaciel** [comment]
Yes, please check this link: https://github.com/Poing-Studios/godot-admob-android/discussions/63

https://discord.gg/YEPvYjSSMk
