### ISSUE TITLE
AdMob not initialized, check your configuration.

### ISSUE THREAD

**Issue by dzosek** [Poing-Studios/godot-admob-android#113]
Admob is not working on my phone.(xiaomi mi a2 lite)
In the godot editor when I click on the button is_initialized() returns false

**Comment by gumaciel** [comment]
Hi, soon i will send to you an `.apk` to you test on the `Example.tscn` if the `.apk` that i will send works, then you are setting something wrong.

**Comment by arnoldochavez** [comment]
Same problem, still no solution? or a way to debug where is the problem?

**Comment by gumaciel** [comment]
Hi, i'm investigating this yet

**Comment by dzosek** [comment]
I spent my game on google play and the ads work and I even earned a few cents :)

**Comment by anisc** [comment]
Same issue for me too, It work perfectly with android tho but with ios I have "AdMob not initialized, check your configuration"
Any solution ?

**Comment by gumaciel** [comment]
@arnoldochavez i'm testing here and everything seems to work, i will close this issue due seems to work for @dzosek  and for me.

If it's still not working please let me know and please try to join our Discord, may i can answer you faster: https://discord.gg/YEPvYjSSMk
