### ISSUE TITLE
[BUG] Admob not initialized, check your configuration

### ISSUE THREAD

**Issue by quantumcode-martin** [Poing-Studios/godot-admob-android#122]
**Describe the bug**

After installing the plugin, I test run and get Admob not initialized, check your configuration.
I tried on my main project and an empty project with Godot 3.4.3 and 3.4.4

**To Reproduce**
1. Follow the guide
2. Run on android

**Expected behavior**
If there is a real problem on my side, a detailed error would be good, otherwise I don't know what I can do.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A3
 - OS: Android
 - Version 11

**Comment by gumaciel** [comment]
Thank you for openning this Issue, can you please try to run again the app? Maybe it works on the second time

I can send to you an .APK to test if will initialize for you or not, so if works, probably you are configuring something wrong

Unfortunately AdMob doesn't tell where is the problem

**Comment by quantumcode-martin** [comment]
Not working on second try.

**Comment by gumaciel** [comment]
Talking with quantum on Discord he manages to work:

```
I tried once again with my project and it works fine !
So everything was fine but I think the issue came from:
1. Phone internal memory was almost full
2. SD card was formatted as internal memory (which is wrong si I formated it to external memory)

So my apps were probably installed on the wrongly configured sd card

Fixed by:
1. Formating SD card to external memory
2. emptying some space on internal memory
```

Closing this issue since it's not actually an issue of the plugin
