### ISSUE TITLE
[BUG] MobileAds.initialize() cannot reinitialize the plugin if it failed once

### ISSUE THREAD

**Issue by SnailRabbids** [Poing-Studios/godot-admob-android#129]
**Describe the bug**
MobileAds.initialize() works only once, cannot reinitialize the plugin.

return code is "0".

**To Reproduce**
off ur internet connection -> run app (AdMob will try to initialize in this step because of autoload) -> AdMob plugin initialization is not completed -> enable internet -> MobileAds.initialize() -> wait for initialization_complete signal -> AdMob plugin is not initialized

**Expected behavior**
If plugin was not been initialized for some reason, MobileAds.initialize() can initialize it.

**Screenshots**
-

**Smartphone (please complete the following information):**
BlueStacks 4.280.0.1022 (Android)

**Additional context**
-

**Comment by gumaciel** [comment]
Thank you for opening this issue!

Related to https://github.com/Poing-Studios/godot-admob-editor/issues/51

**Comment by gumaciel** [comment]
Closing the issue, as it seems to be something from the editor plugin: https://github.com/Poing-Studios/godot-admob-editor/issues/51

This behavior should be normal for AdMob but I will look into it
