### ISSUE TITLE
Pre-loading multiple Ads

### ISSUE THREAD

**Issue by flaming-toast** [Poing-Studios/godot-admob-android#133]
Hello! First off, this plugin is amazing and thank you so much for your hard work!

I was integrating this plugin into my game and realized that the plugin cannot seem to handle loading multiple rewarded ads - is this observation correct?

I have two currencies in the game that can be doubled individually if the player watches a rewarded ad. So, I tried to preload two rewarded videos in the game. However, after looking at the plugin source code, it seems that the plugin only shows the most recently loaded one (if load is called multiple times, aRewardedAd variable is reassigned to the last loaded ad)

Is it against some AdMob policy to do this? Or is it just that the current code doesn't support this situation?

**Comment by gumaciel** [comment]
Thank you for opening this issue.

Actually this is only a feature that we don't have, but will be good if implemented.

I think there's nothing about the AdMob policy.

**Comment by flaming-toast** [comment]
Thanks a lot for the response! Yeah, I think a lot of mobile games do preload multiple ads, so I don't think Admob would have a problem with this.

I'm not familiar with Java, but I think it should be simple to implement..? Instead of saving the loaded ad into a variable, maybe we can use a Dictionary/Hash table to map the ad unit names to the RewardedAd instance, and load_rewarded() would just take an extra name as an argument. This issue would also apply to the iOS version as well. What do you think?

**Comment by gumaciel** [comment]
Hi, yes, it should be possible, I've never tried because i was focusing on implement "key features" of AdMob.

It should not be hard, maybe we can use this: https://developers.google.com/admob/android/native/start#loading_ads

I will only be able to work on it after finishing some existing AdMob issues, if possible, try to implement it, maybe these documentations will help: 

https://github.com/Poing-Studios/godot-admob-android/wiki/Android-Plugin
https://developers.google.com/admob/android/quick-start

**Comment by ebudagov** [comment]
Hello everyone, just faced the same issue with lack of support for multiple ad units. It would be graet to have this feature added

**Comment by Indieveloper** [comment]
I'm also looking for this feature. It helps for analytics to see which types of ads work.
And it allows the usage of the AdMob ad-unit setting of Frequency Capping. The workaround right now is to manually cap it in code itself. And if there's also API calls to obtain info about Frequency Capping, that itself would be nice too.

**Comment by gumaciel** [comment]
Thank you guys, this Issue will be priority after the Plugin migration for Godot 4.0

**Comment by gumaciel** [comment]
Closing since it was done on https://github.com/Poing-Studios/godot-admob-plugin/issues/82 and https://github.com/Poing-Studios/godot-admob-android/issues/167, development is finished but need to test.

Check the future status of iOS here: https://github.com/Poing-Studios/godot-admob-ios/issues/45
