### ISSUE TITLE
[BUG] Plugin crashes under Android 13 on autoload

### ISSUE THREAD

**Issue by Telestes** [Poing-Studios/godot-admob-android#143]
### Godot version

3.5

### Plugin version

v 2.1.1

### Phone information

Google Pixel 5 with Android 13

### Issue description

First, I like to thank you for this great Godot AdMob plugin!

Using your plugin in my new Godot Android app works fine under Android 7 to 11 (tested all beside 12). Today, I installed my app on a Google Pixel 5 phone with the new Android 13 and unfortunately it crashes on startup (autoload). Then I disabled your plugin from the project without changing any other code and all works fine. It appears that your plugin crashes in the autoload phase under Android 13. Did you test your plugin under Android 13 or can anyone confirm that it works under Android 13?

Best regards,
Telestes

### Steps to reproduce

Using plugin under Android 13 crashes on Google Pixel 5

**Comment by gumaciel** [comment]
Please test with the latest plugin versions to check if still happens: 

https://github.com/Poing-Studios/godot-admob-editor/releases/tag/v1.3.2
https://github.com/Poing-Studios/godot-admob-android/releases/tag/v2.1.2

**Comment by Telestes** [comment]
I've tested it and can confirm that the new version runs fine under Android 13 on a Google Pixel 5. The described bug doesn't happen anymore. Thank you, for the update and the great plugin!

**Comment by gumaciel** [comment]
Thank you! I will close this Issue since it's already fixed on latest version.
