### ISSUE TITLE
Invalid link from Wiki to GODOT Android Plugin Documentation

### ISSUE THREAD

**Issue by luc4smoreira** [Poing-Studios/godot-admob-android#144]
### Godot version

not applicable

### Plugin version

not applicable

### Phone information

not applicable

### Issue description

Fix the broken link `Android plugins: https://docs.godotengine.org/pt_BR/stable/tutorials/plugins/android/android_plugin.html`

Using this new one: https://docs.godotengine.org/en/stable/tutorials/platform/android/android_plugin.html

### Steps to reproduce

Access [Android Plugin Wiki](https://github.com/Poing-Studios/godot-admob-android/wiki/Android-Plugin)

At  
> Understanding the Plugin

Check the link described in the sentence:

`We strong recommend you read how to create Android plugins: https://docs.godotengine.org/pt_BR/stable/tutorials/plugins/android/android_plugin.html`

Click on the link and verify the result: **"Page not found"**

### Additional context

![Screen Shot 2022-11-14 at 11 36 58](https://user-images.githubusercontent.com/9322152/201687384-295aceb8-cee6-47b3-8b07-01f6b37456d3.png)

**Comment by gumaciel** [comment]
Ty we will fix it

**Comment by gumaciel** [comment]
Thank you! Fixed
