### ISSUE TITLE
I get a warning that could not be found when compiled with gradle libc++_shared.so and libgodot_android.so libraries?

### ISSUE THREAD

**Issue by mrParabol** [Poing-Studios/godot-admob-android#146]
### Godot version

3.5.1

### Plugin version

1.3.2

### Phone information

android 9

### Issue description

After compiling as APK, I get the following warning when I run the application.
![Ekran Görüntüsü_alan seç_20221208043110](https://user-images.githubusercontent.com/28789841/206334281-2cb5d4e3-d6a2-4e12-a185-5b5907ff538a.png)

### Steps to reproduce

I received a warning from Gradle during the compilation.

**Comment by gumaciel** [comment]
Thank you for opening this issue we will investigate this

**Comment by gumaciel** [comment]
Are you getting these warning on Android Studio compilation (Plugin development) or on Godot export?

Try to update the Java/Gradle of your PC to check if these warnings still appear.

**Comment by gumaciel** [comment]
Closing the issue because this doesn't seem to be from the plugin
