### ISSUE TITLE
Is there any support to show the ad in the upper right corner of the screen?

### ISSUE THREAD

**Issue by mrParabol** [Poing-Studios/godot-admob-android#147]
Is there any support to show the ad in the upper right corner of the screen? for banner ads.

**Comment by gumaciel** [comment]
Currently does not support, but maybe can be implemented on the future, we need to search if it's recommend to do that on AdMob.

**Comment by gumaciel** [comment]
Unfortunately I have some other priorities in mind for the Plugin, which I won't be able to work on this Issue, it would be nice if someone could help with this.

Of course we need to analyse if this Issue is really necessary for the majority of Plugins or Clients users.

**Comment by gumaciel** [comment]
Done on #167
