### ISSUE TITLE
Issue with ad load

### ISSUE THREAD

**Issue by SnowmanPlayz** [Poing-Studios/godot-admob-android#151]
### Godot version

3.5.1

### Plugin version

v2.0.0

### Phone information

Android 30

### Issue description

My ads are not loading.
What can I do?

### Steps to reproduce

i

**Comment by gumaciel** [comment]
Hi, please check this: https://support.google.com/admob/answer/9469204?hl=en

Most common problems are: You need to wait up to 24 hours after you create your account.

Please always test with Test Ads https://developers.google.com/admob/android/test-ads#demo_ad_units

**Comment by gumaciel** [comment]
Hi @SnowmanPlayz any update?

**Comment by gumaciel** [comment]
Closed due to no response
