### ISSUE TITLE
Provide Missing Release Artficat for Godot 3.5.2

### ISSUE THREAD

**Issue by knightofiam** [Poing-Studios/godot-admob-android#165]
### Godot version

Godot Mono 3.5.2 Stable

### Plugin version

2.1.3

### Phone information

Android SDK 32

### Issue description

GitHub Actions build expects to download an AdMob release artifact matching the latest stable Godot version for Godot 3.x, which is 3.5.2. The build fails because there is no such artifact, as the latest 3.x release is for 3.5.1.

```
 --2023-04-05 12:34:31--  https://github.com/Poing-Studios/godot-admob-android/releases/download/v2.1.3/android-mono-template-v3.5.2.zip
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-04-05 12:34:31 ERROR 404: Not Found.
```

### Steps to reproduce

Attempt to download AdMob for Godot Mono 3.5.2 as expected using [this link](https://github.com/Poing-Studios/godot-admob-android/releases/download/v2.1.3/android-mono-template-v3.5.2.zip), `ERROR: 404 Not Found`.

**Comment by knightofiam** [comment]
@gumaciel Ads aren't working in exported 3.5.2 projects on a physical device while using the 3.5.1 Admob artifact. This is preventing me from upgrading my client's app. Any ideas?

**Comment by gumaciel** [comment]
Sorry about this, this will be solved soon.

Please note: on v2.1.3 and towards there's will be no more `android-mono-template`, it will be called just `android-template` as seen on: https://github.com/Poing-Studios/godot-admob-android/releases/tag/v2.1.3

**Comment by gumaciel** [comment]
The plugin has been released: https://github.com/Poing-Studios/godot-admob-android/releases/download/v2.1.3/android-template-v3.5.2.zip
