### ISSUE TITLE
Outdated documentation for godot 4.03

### ISSUE THREAD

**Issue by liyaowhen** [Poing-Studios/godot-admob-android#170]
### Godot version

4.03

### Plugin version

v2.1.4

### Phone information

Samsung A32 (irrelevant to the bug)

### Issue description

Many of the stuff on the documentation for the admob plugin is outdated. The part where you turn on the custom build template is non existent in godot 4.x. It has been renamed to "Enable gradle". And for some reason, the plugin section in the android export settings is non-existent making it impossible to enable the plugin for android build. This seems to have been removed in godot 4.

### Steps to reproduce

1. Download godot 4.03
2. Install Eclipse Temurin OpenJDK 11
3. Install and add required sdk and ndk for godot
4. Install android build template
5. Install Admob plugin
6. Install android custom build template
7. Add android for export
8. Install android admob plugin in the android/plugins folder

### Additional context

![Godot_v4 0 3-stable_win64_YyPHXGXFmv](https://github.com/Poing-Studios/godot-admob-android/assets/72400519/5d9e6165-4ef3-495f-b944-6c58383f5752)

there is no "Enable Custom Build Template" or "Plugins" section.

**Comment by gumaciel** [comment]
Ty for opening this issue, I will check this soon

**Comment by gumaciel** [comment]
Hi @liyaowhen some error appear on the Output area?
![Captura de Tela 2023-06-26 às 20 56 33](https://github.com/Poing-Studios/godot-admob-android/assets/20030153/062a890a-ea11-44c1-bfba-3ef1d1b3e47c)


This is strange because it should work normally for Godot 4

**Comment by liyaowhen** [comment]
I got it to work by Uninstalling java then reinstalling it. For some reason it had a weird gradle error saying that my java version is too high, even though I was using java 8

**Comment by gumaciel** [comment]
Nice I will close this issue since was fixed by the user
