### ISSUE TITLE
I don't see any test ads when i export to my Android device

### ISSUE THREAD

**Issue by javrocks** [Poing-Studios/godot-admob-android#183]
### Godot version

3.5

### Plugin version

v2.1.4

### Phone information

Motorola with Android 10

### Issue description

I'm using android-template ver 3.5 as my plugin and i updated the AndroidManifest.xml with the Sample AdMob app ID here: https://github.com/Poing-Studios/godot-admob-android/
I have Use custom build turned on and The apk exports fine with no errors. Yet when i open the app i see no ads.
When i export the same project to IOS i see the test ads 
How do i fix this ? 

### Steps to reproduce

no steps

**Comment by gumaciel** [comment]
Hi, what error code do you get when you try to load an ad?

**Comment by javrocks** [comment]
I didn't get an errror code it seems like i just had to turn on features in the Export menu
I turned on Custom Build, Admob, Internet and Access Network State and i can now see test ads 
Oh and i also had to add Some Android Network Permissions code to my AndroidManifest.xml
It wrk now tho, it seems 👍🏽

**Comment by gumaciel** [comment]
Nice, i will close this issue
