### ISSUE TITLE
3.0.0 Plugin is failing

### ISSUE THREAD

**Issue by DavidOcacho** [Poing-Studios/godot-admob-android#188]
### Godot version

4.1.1

### Plugin version

v3.0.0

### Phone information

Samsung S22 Android 13

### Issue description

The Ad Mob Android plugin isn't working. If I disable it my app works fine on my phone

### Steps to reproduce

1. Make sure to have Ad Mob enabled on your export
2. Export or Remote debug the project

![image](https://github.com/Poing-Studios/godot-admob-android/assets/126606809/4073dee2-91f7-4ff1-938d-1d234d5e70d5)

**Comment by DavidOcacho** [comment]
EDIT: I tested 2.1.4 and it's also failing

**Comment by gumaciel** [comment]
Hi, what error are you getting?

**Comment by DavidOcacho** [comment]
The game just crashes, I can't tell you the exact error because the game doesn't show up. 

The only thing that I can see on the godot terminal is: reverse result: 0

**Comment by gumaciel** [comment]
![image](https://github.com/Poing-Studios/godot-admob-android/assets/20030153/fe1e6636-8284-41c5-8a33-9cfdb6be8d48)
have you did this?

**Comment by gumaciel** [comment]
please try to check `adb` to see the cause of crash

**Comment by DavidOcacho** [comment]
omg, totally my bad, I was using a "/" character instead of "~" on the android:value, not idea why, so sorry! thanks!
