### ISSUE TITLE
Native ads support

### ISSUE THREAD

**Issue by DavidOcacho** [Poing-Studios/godot-admob-android#189]
### What feature or improvement would you like to see?

First of all, nice plugin, it's pretty handy!

It would be awesome to have the possibility to also create Native ads so we can have a better integration in our applications.
As an example, just load a video ad in some part of our app but the user can scroll down to avoid the ad. 

Thanks!

**Comment by gumaciel** [comment]
Hello, for now, native ads will not be implemented for the plugin, it is very complicated to deal with standard Android/iOS objects together with Godot, read more here: #75. Maybe in the future it will be implemented, we need contributors for this.

We have a higher priority in implementing the Open Ads App: #141
