### ISSUE TITLE
Application crashes after opening ads

### ISSUE THREAD

**Issue by half-twice** [Poing-Studios/godot-admob-android#190]
### Godot version

4.1.1

### Plugin version

v3.0.0

### Phone information

Samsung S20+ (Android 13 - OneUI 5.1)

### Issue description

- Application crashes (APK) when returning to the application after clicking on an ad (banner / interstitial tested), both in the sample project and in implementation in my app
- No errors are returned to Godot (if run as Remote Debug Export)
- Ads are displayed correctly and if closed (close interstitial) there are no issues

Note: No issues with sample project or implementation in app for iOS devices.

### Steps to reproduce

1. Banner ads and interstitial ads tested using sample project at addons/admob/sample/Main.tscn.
2. On clicking advertisement navigates to web browser (Chrome)
3. Application screen is black in App Switcher, with no ability to return to application / application has crashed

**Comment by gumaciel** [comment]
Thank you for reporting this issue, we will investigate this

**Comment by gumaciel** [comment]
This bug is the same as https://github.com/Poing-Studios/godot-admob-android/issues/187

This problem seems to me to be a Godot problem, as it doesn't happen in Godot 3, only in Godot 4.

If possible, try to do what I said in the comment:
> If possible, try to create a simple Android AdMob plugin with the functionality you need and check if the same bug occurs.
