### ISSUE TITLE
Just question

### ISSUE THREAD

**Issue by trash-max** [Poing-Studios/godot-admob-android#203]
### Is your feature request related to a problem? If so, please describe.

When I make a custom build with the required library version, the poing-godot-admob-core-*-release.aar file it is created in two places:
core:
/godot-admob-android/src/core/build/outputs/aar/
and ads:
/godot-admob-android/src/ads/build/outputs/aar/
It looks very much like the files are identical, but still which one should I use?
Thanks.

### What feature or improvement would you like to see?

Using custom builds for this plugin

**Comment by gumaciel** [comment]
Hmm sorry, I didn't understand, are you making this build in Android Studio or you downloaded it in the GitHub Releases link?

**Comment by trash-max** [comment]
> Hmm sorry, I didn't understand, are you making this build in Android Studio or you downloaded it in the GitHub Releases link?

Hi.
Show you my steps (using Linux, if important).
1. I clone this repository
2. set up SDK and JAVA ways
3. Download and put *.aar file
4. And run "./gradlew build"

As result poing-godot-admob-core-*-release.aar builds twice, in different folders. 
(in /src/**core**/build/outputs/aar/ and /src/**ads**/build/outputs/aar/)

**Comment by gumaciel** [comment]
I got it.

Yes, this is normal because when the **core** builds it generates the `.aar` into `build/outputs/aar` folder of the project, and on **ads** it copy the `.aar` of **core** into `build/outputs/aar` folder of the project, so it seems to be duplicated

**Comment by trash-max** [comment]
Ok.
Thank you 😊
