### ISSUE TITLE
Update for godot 4.2.0 stable

### ISSUE THREAD

**Issue by LotusLegends** [Poing-Studios/godot-admob-android#211]
### Is your feature request related to a problem? If so, please describe.

Add admob support for godot 4.2.0 stable.

### What feature or improvement would you like to see?

Add admob support for godot 4.2.0 stable.

**Comment by gumaciel** [comment]
Hi, the plugin already has support for 4.2, are you facing some error?

**Comment by FabPei** [comment]
Not the same game, but i was confused because no "plugins" folder was created in the projects "android" folder. Did that change with 4.2 and the new Android V2 plugin system?

**Comment by gumaciel** [comment]
It shouldn't, if it doesn't exist, try creating a folder, I'll look into that

**Comment by gumaciel** [comment]
It shouldn't, if it doesn't exist, try creating a folder, I'll look into that

**Comment by gumaciel** [comment]
@FabPei Yeah, doesn't exist anymore due `v2` Android plugin system.

But you only need to create a folder "plugin" and then add the plugin binaries and then it will work 
![Screenshot 2023-12-17 at 10 24 34](https://github.com/Poing-Studios/godot-admob-android/assets/20030153/f5a81609-359e-48ec-93c0-1435f8a0dc69)

Closing this issue since it's working for v4.2+

**Comment by FabPei** [comment]
Hi, yeah it definitely works by just creating a folder, was rather confused before trying the plugin because i thought it doesnt work anyway due the 4.2 change and the missing folder.  Thanks!

**Comment by LotusLegends** [comment]
> @FabPei Yeah, doesn't exist anymore due `v2` Android plugin system.
> 
> But you only need to create a folder "plugin" and then add the plugin binaries and then it will work ![Screenshot 2023-12-17 at 10 24 34](https://private-user-images.githubusercontent.com/20030153/291064725-f5a81609-359e-48ec-93c0-1435f8a0dc69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4Nzc2MDgsIm5iZiI6MTcwMjg3NzMwOCwicGF0aCI6Ii8yMDAzMDE1My8yOTEwNjQ3MjUtZjVhODE2MDktMzU5ZS00OGVjLTkzYzAtMTQzNWY4YTBkYzY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDA1MjgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNDBhNWQwZTkzZDdiZDI2ZWFhOWY5Y2QyNTc3ZWVjNjZhYjg1ZGJmNDIxMTI3NDQ3ZTNkMjE4ZjEyMjIwYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IRUtFZWOwE4twKeP1DkJ04aNyAWdSj4UrWbqqY6548o)
> 
> Closing this issue since it's working for v4.2+

Bro this work for you?, you can give me exported apk file?

**Comment by FabPei** [comment]
@LotusLegends it works in 4.2. I just followed the instructions
