### ISSUE TITLE
Provide Custom Export Template

### ISSUE THREAD

**Issue by LotusLegends** [Poing-Studios/godot-admob-android#213]
### Is your feature request related to a problem? If so, please describe.

Need Godot 4.2.0 stable export template for android with all arm support because many developer face export issue while using custom build.

### What feature or improvement would you like to see?

Provide Custom Export Template Godot 4.2.0 stable for fast export and easy to use .

**Comment by gumaciel** [comment]
Sorry I suppose it's not possible, the way which Android Plugins works on Godot don't need to have this.

Are you facing some difficult while exporting?

**Comment by gumaciel** [comment]
Closing the issue since seems to not be necessary

If you need some help to export I can help you, or join our discord on the README.md
