### ISSUE TITLE
v2.1.6 crashing without error

### ISSUE THREAD

**Issue by Molly-Rose-Pastel** [poing-studios/godot-admob-android#215]
### Godot version

3.5.3

### Plugin version

v2.1.0

### Phone information

Galaxy A20e

### Issue description

I just upgraded from 2.1.5 to 2.1.6 and the plugin crashes without any errors. Nothing showing up in logcat.
When I revert back to 2.1.5 everything is working properly.

### Steps to reproduce

I downloaded the 2.1.6 .gdap and .aar files and replaced the files from version 2.1.5 in android/plugins with them.

**Comment by gumaciel** [comment]
Hi, you also need to update your `godot-admob-plugin`, please test with this one: https://github.com/poing-studios/godot-admob-plugin/releases/tag/v2.0.1

**Comment by gumaciel** [comment]
Hi @Molly-Rose-Pastel , any update?

**Comment by gumaciel** [comment]
I'm closing this issue since seems to be fixed here and lack of response

if this issue still happens even after updating your plugin, please re-open it
