### ISSUE TITLE
[FEATURE] Mediation

### ISSUE THREAD

**Issue by gumaciel** [Poing-Studios/godot-admob-android#28]
Android: https://developers.google.com/admob/android/mediate
iOS: https://developers.google.com/admob/ios/mediate

Why mediate is good: https://www.youtube.com/watch?v=ie6cwaaOFrY

**Comment by hamzaydia** [comment]
@gumaciel any update?

**Comment by gumaciel** [comment]
hi @hamzaydia it will be done on: https://github.com/Poing-Studios/godot-admob-android/issues/167

**Comment by gumaciel** [comment]
Closing since it was done on https://github.com/Poing-Studios/godot-admob-plugin/issues/82, development is finished but need to test.

Currently it's only supporting Vungle (Liftoff Monetize), Meta and AdColony for https://github.com/Poing-Studios/godot-admob-android/issues/167.

Check the future status of iOS here: https://github.com/Poing-Studios/godot-admob-ios/issues/45
