### ISSUE TITLE
[FEATURE] Easily change gdpr settings after they have already been set

### ISSUE THREAD

**Issue by Xioor** [Poing-Studios/godot-admob-android#57]
**Is your feature request related to a problem? Please describe.**
To be gdpr compliant, it is required that the user can easily change the gdpr settings from within the app at any moment they want. For example, having a button called gdpr in the settings of your game could show the original gdpr prompt when you first launch the game. For iOS and Android

**Describe the solution you'd like**
Just have a function that can be called from GD that would show the gdpr prompt again.

**Describe alternatives you've considered**
None that I can think of

**Additional context**
Reference https://www.sourcepoint.com/blog/optimizing-user-opt-in-on-ios-14-idfa-changes/

**Comment by gustavottc** [comment]
I think this is not possible, because from what I've researched, UMP needs to be started before [`MobileAds.initialize()`](https://stackoverflow.com/a/63232045).
> In that case be sure to call it before MobileAds.initialize, so that no cookies are used.

And we [can't initialize the AdMob more than once](https://developers.google.com/admob/android/quick-start#initialize_the_mobile_ads_sdk) 

> This needs to be done only once, ideally at app launch.

And the area when [`Reset content state`](https://developers.google.com/admob/ump/ios/quick-start#reset_consent_state) is in [`Testing`](https://developers.google.com/admob/ump/ios/quick-start#testing)

Probably the user will need to restart the game to this works, until he don't do that, the consent will not change.

But i will give a try to see if this can work, thank you for opening the Issue!

**Comment by gustavottc** [comment]
Yeah, i tested here and the user will need to restart the game to this works, when i reset the consent after being consented nothing happens until i restart the app.

I'm just afraid if this method is only for testing or it can also be for production, if the user wants to select another consent.

I created a conversation here on Google Mobile Ads SDK developers: https://groups.google.com/g/google-admob-ads-sdk/c/F_QHhhE5Qro if they say can be too for production, i will do that

**Comment by Xioor** [comment]
Great thank you for looking into this! How can you tell that you needed to reset? Like how do you know the gdpr settings have been set to something else? Just curious. Also in previous games or api, that is what I did. I had a gdpr button in the settings, and then when you press it and change your preference, the screen becomes black and it says gdpr settings changed, please restart the app. It's not very user friendly, but it at least gives the user the ability to reset the settings. Maybe in the api comment you could say, "you need to restart the app for changes to take into effect". That way developers knows. The developers could then do what I do, or they could show a dismissible prompt saying "Gdpr settings changed, effect will take place once application is restarted" or something along those lines.

**Comment by Xioor** [comment]
Also looks like I don't have permission to chat in the google conversation you have. Do you mind asking as well, just to make sure if the user needs to restart the application after they do UMPConsentInformation.sharedInstance reset?

**Comment by gustavottc** [comment]
Probably i wont need to restart the app, just try to call again the user consent, i will try again tomorrow.

We can know the GDPR settings have been set by the signal `consent_status_changed(consent_status_message)`

It can be four type of status: https://developers.google.com/admob/ump/android/quick-start#present_the_form_if_required

Today the User consent appear when the app starts, which i think it will be better due of this: https://stackoverflow.com/a/63232045, but i can make a option to: Appear the UMP when initialize the AdMob and also a function to try to appear the UMP, but to appear the UMP again we will need to reset the consent.


> Also looks like I don't have permission to chat in the google conversation you have. Do you mind asking as well, just to make sure if the user needs to restart the application after they do UMPConsentInformation.sharedInstance reset?

To write on the conversation you need to participate to the group on the main page: https://groups.google.com/g/google-admob-ads-sdk, and yes, i can do that

**Comment by gustavottc** [comment]
hey @Xioor , they answered: https://groups.google.com/g/google-admob-ads-sdk/c/F_QHhhE5Qro

Also i created a thread here: https://support.google.com/admob/thread/108484133/the-function-umpconsentinformation-sharedinstance-reset-is-just-for-test-or-can-be-used-on-produc?hl=en

**Comment by Xioor** [comment]
Great thank you for so much! I also contributed to the conversation. Great work :)

**Comment by gustavottc** [comment]
So **Teejay** answered this:

There are 2 ways for you to revoke/reset the consent of your app's users.
- You may to [request consent](https://developers.google.com/admob/ump/android/quick-start#request_the_latest_consent_information) again to trigger the revocation of the previous consent. You may create a method for this, then put an option in your app settings section called 'modify consent' that will run the created method.
- You will need to set the **UMPConsentStatus** to **UNKNOWN** first or by [resetting](https://developers.google.com/admob/ump/ios/quick-start#reset_consent_state) the consent by following this guide.

I will do this until the end of this week, I am currently working on a Plugin Editor that will replace admob_api: https://github.com/Poing-Studios/Godot-AdMob-Editor-Plugin

It is still in the pre-alpha phase, when i finish i will do that.

Thank you so much for helping the Plugin be better!

**Comment by gumaciel** [comment]
Hey @Xioor  i'm almost finishing, but i'm not able to test because AdMob send me this:

`Your GDPR messages and settings in Funding Choices are being transferred to Ad Manager and AdMob. Messages targeting sites (not apps) with no recent traffic will be unpublished and may be republished in Ad Manager. We're also merging the vendors you've selected in the European Union Consent Messages in Funding Choices with the ad technology providers displayed on your Ad Manager or AdMob EU User Consent page. All self-use purposes are now defined at the account level. New users will see the combined list of vendors in their GDPR messages as soon as we complete the transfer. Review your ad technology vendors and providers before June 1st.`

https://support.google.com/fundingchoices/answer/10648187

And they still don't finished this.

**Comment by gumaciel** [comment]
@Xioor I have just commited the changes, please try it out.

**Comment by Xioor** [comment]
@gumaciel I am assuming after June 1st it should be good to test? Thanks for the update!

**Comment by gumaciel** [comment]
@Xioor Yes, but they don't tell nothing yet, still not working the GDPR :(

**Comment by gumaciel** [comment]
@Xioor Hi, it's working for you? They still don't transfer the Funding Choices to AdMob for me

**Comment by gumaciel** [comment]
@Xioor I tested here on my Android device and seems to work everything fine

i invite you to test the new version of the Plugin, i just released the version:

Editor Plugin: v1.0.0
iOS Plugin: v2.0.0
Android Plugin: v2.0.0

Editor: https://github.com/Poing-Studios/godot-admob-editor/releases/tag/v1.0.0
Android: https://github.com/Poing-Studios/godot-admob-android/releases/tag/v2.0.0
iOS: https://github.com/Poing-Studios/godot-admob-ios/releases/tag/v2.0.0

Soon i will try to work on this issue of "NSUserTrackingUsageDescription"

I will close this issue, if this doesn't fix to you let us know.
