### ISSUE TITLE
[BUG] Unable to Connect to Signals Using C# Script When Accessing AdMob Singleton

### ISSUE THREAD

**Issue by atlasapplications** [Poing-Studios/godot-admob-android#93]
**Describe the bug**
I'm unable to connect to any of the AdMob singleton signals when using a C# script. An error of InvalidParameter is given when I attempt any connection. When listing all of the singleton's signals, only script_changed is available, so no other signals are being registered with the C# Mono classes. This might be happening because of the use of GodotLib.calldeferred in AdMob.java. A solution could be replacing the current implementation with emitSignal because other similar projects have exhibited this bug and have since migrated to this method. Two prominent examples include Shin-Nil's AdMob plugin and Godot's GodotGooglePaymentBilling.

Here is some documentation on the issue:

https://github.com/godotengine/godot/issues/40481
https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/issues/55
The issue exhibited with other plugins

https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/pull/56
https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/pull/56/commits/b557e134fd8dc1185d448ab0b3c3f28f3f1595ac
Potential solutions

**To Reproduce**
Instead of using the GDScript editor plugin, just use a C# script to initialize the AdMob plugin and try connecting to any of the signals.

**Expected behavior**
The signals should connect.

**Smartphone (please complete the following information):**
So far, the only platform I tested this on is Android.

**Comment by gumaciel** [comment]
Hi @atlasapplications thank you for opening this issue, we will check it out

**Comment by gumaciel** [comment]
Hey @atlasapplications as i tested here it's fully working with C# script, i will do an update on [Editor Plugin](https://github.com/Poing-Studios/godot-admob-editor) soon to you try it out.

**Comment by gumaciel** [comment]
@atlasapplications Please try it out:

https://github.com/Poing-Studios/godot-admob-editor/releases/tag/0.4.2

**Comment by atlasapplications** [comment]
> @atlasapplications Please try it out:
> 
> ## https://github.com/Poing-Studios/godot-admob-editor/releases/tag/0.4.2
> To try the `.cs` Script you need to change the `GDScript` to `C#`:
> 
> ![Captura de Tela 2021-08-12 às 23 29 58](https://user-images.githubusercontent.com/20030153/129296646-ad043984-034b-4151-b2f5-f01b228af391.png)
> 
> ![Captura de Tela 2021-08-12 às 23 30 42](https://user-images.githubusercontent.com/20030153/129296672-69f8d348-1ed5-42f7-9776-d7f6a4063885.png)
> 
> ![Captura de Tela 2021-08-12 às 23 30 56](https://user-images.githubusercontent.com/20030153/129296687-e723f18b-5a2f-4068-ad03-d3fad56ed311.png)
> 
> Also, the `Example.tscn` is located here:
> ![Captura de Tela 2021-08-12 às 23 32 38](https://user-images.githubusercontent.com/20030153/129296815-3795a08a-748f-455b-b99c-4f3fa4c5697c.png)

I will try it out. Thank you for taking a look at it!

**Comment by atlasapplications** [comment]
I tested the plugin and it doesn't appear to have changed at all. The only differences is that Example.cs was added, and all that does is access the node MobileAds which is written in GD Script. It appears the plugin works fine when the AdMob Singleton is initialized in GD Script, but the original issue is that when a C# script initializes the AdMob singleton that's when the signals aren't able to connect.

To reproduce the issue, maybe try writing a portion of the MobileAds.gd with a C# script?

**Comment by gumaciel** [comment]
Hey @atlasapplications I think you are doing something wrong, because on my phone is everything working with the C#/mono Script:

![Screenshot_2021-08-14-19-09-47-589_org.godotengine.admobaddon.jpg](https://user-images.githubusercontent.com/20030153/129461309-56f8f185-4359-41fc-95e7-1f16aa50c72a.jpg)

**Comment by gumaciel** [comment]
@atlasapplications 

Please watch to this tutorial: https://www.youtube.com/watch?v=MW4hUR0d9lc&ab_channel=PoingStudios

**Comment by gumaciel** [comment]
Is there anything you are finding complicated using the Plugin?

I know the Tutorial is not good, but it's just me to make these videos and it's a lot for one person to do, but I hope it helps you.

**Comment by atlasapplications** [comment]
The plugin looks good, it doesn't seem like it's complicated at all. I was just seeing if I could create my own way of accessing the AdMob singleton for my own specific needs. I followed your tutorial and it seems like I'm setting my project up correctly. Attached I have a simplified version of the C# script I'm using to access the AdMob singleton. Maybe you can try it out on your own setup to see if you can reproduce the issue that way? 

So instead of using the GDscript editor plugin, just use this script (rename to .cs) and a Control Label to update what's happening when it's initialized.

[TestAdMob.txt](https://github.com/Poing-Studios/godot-admob-android/files/7015122/TestAdMob.txt)

![code_sample](https://user-images.githubusercontent.com/60163495/130087250-58850f50-db9a-436a-87ce-aa01453877f3.png)

**Comment by gumaciel** [comment]
Hey, i will give a look but i don't think this is necessary at all, because the "MobileAds.gd" script already does everything the Plugin needs

If you just need something is not on the "MobileAds.gd", just try to extends him.

But i will give a look on to how put C# Script to fully work and why is not working in some days, I'm afraid to switch from "calldeferred" to "EmitSignal" because the iOS Plugin doesn't have this support (as i know) and would probably generate some kind of bug.

**Comment by gumaciel** [comment]
@atlasapplications  I release a new version of Plugin, probably you will be able to do what you want now

i invite you to test the new version of the Plugin:

Editor Plugin: v1.0.0
iOS Plugin: v2.0.0
Android Plugin: v2.0.0

Editor: https://github.com/Poing-Studios/godot-admob-editor/releases/tag/v1.0.0
Android: https://github.com/Poing-Studios/godot-admob-android/releases/tag/v2.0.0
iOS: https://github.com/Poing-Studios/godot-admob-ios/releases/tag/v2.0.0

**Comment by gumaciel** [comment]
Hi @atlasapplications any news about the new version?
