### ISSUE TITLE
[FEATURE] Multiple Banners displayed at once

### ISSUE THREAD

**Issue by IsaaacD** [Poing-Studios/godot-admob-android#98]
**Is your feature request related to a problem? Please describe.**
I'm interested in having multiple banners and the current API doesn't appear to allow for it. 

**Describe the solution you'd like**
I'd like to have a smart banner displayed at the bottom during the usage of my app, but I'd also like to add a leaderboard or another size when going into other menus at some points, ideally without removing the smart banner. Maybe there's a way rather than putting `MobileAds.hide_banner()`, we could have `var banner = MobileAds.load_banner()` and then `banner.hide_banner()` to explicitly hide a banner that's displayed on a menu.

**Describe alternatives you've considered**
An alternative would be maybe to pass a name of the banner to `MobileAds` and it could keep references to the banners.

**Additional context**
None

**Comment by gumaciel** [comment]
Hi, unfortunately I don't think it's possible what you want, first of all it is outside the best AdMob practices, watch this video: https://youtu.be/BE2K1IpXaSI?t=196

There are also other things:

1. To make this change I would need to change the architecture of both the Plugin for both Android and iOS, and that would take a lot of time and I don't think it's worth the effort for something that AdMob itself doesn't recommend.
2. Currently, if you create more than one banner and try to delete the first one, it will not be possible to delete it as it will lose its reference. (It would work if we change the Plugin architecture, but then we go back to 1.)
3. If you don't follow the best practices that AdMob recommends, your app's ads may be disabled until you fix: https://youtu.be/yTnqcz6RJ-4?t=70

**Comment by IsaaacD** [comment]
Thanks @gumaciel, that makes sense. How would be the best way to swap the banners than? I tried the following without much luck. Should I be hooking into the signals to trigger some of these methods?
```
  MobileAds.banner_hide() ## hides smart banner
  MobileAds.config.banner.size = "MEDIUM_RECTANGLE"
  MobileAds.banner_load()
  MobileAds.banner_show() ## shows next banner
 ```

**Comment by gumaciel** [comment]
Yes, you can change the size like you did on the example you showed, should work fine
